### ISSUE TITLE
Unable to complete run

### ISSUE THREAD

**Issue by megan201296** [TTP0/drone#1]
I can enter all the info but when I get to analyst comments, I cannot finish the submission. The tutorial video says to hit enter but that just takes me to a new line. Not sure if this is a bug or what.

![screen shot 2018-08-05 at 6 54 48 pm](https://user-images.githubusercontent.com/19668285/43691458-86ffcd0a-98e2-11e8-9efb-5fcc3c3dd661.png)

I am running this on OSX.

**Comment by dfirence** [comment]
You are welcome, heres another video we are posting that walks you in depth with the shell and its built commands. 

Wiki Article coming right up!


https://youtu.be/9mBsdoUI_BE

Sent Via Mobile

**Comment by dfirence** [comment]
Before closing the submmited issue we are writing a Wiki Article.

**Comment by dfirence** [comment]
### Article Complete

https://github.com/TTP0/drone/wiki/TTP0-DRONE---Observables-Shell-&-Commands-Tutorial
